import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { createBusinessProfile, getBusinessProfile, removeBusinessProfileLogo, updateBusinessProfile, uploadBusinessProfileLogo } from "../api/businessProfiles";
import type { BusinessProfileInput } from "../api/types";
import { businessProfileToInput, emptyBusinessProfileInput, normalizeBusinessProfileInput } from "../businessProfiles/businessProfileHelpers";
import "./BusinessProfilePages.css";
import "./BusinessProfileUx.css";
import "./BusinessProfilePolish.css";

const logoTypes = ["image/png", "image/jpeg", "image/webp"];
const maxLogoSize = 5 * 1024 * 1024;

export function BusinessProfileFormPage({ mode }: { mode: "create" | "edit" }) {
  const { profileId } = useParams(); const id = Number(profileId); const navigate = useNavigate();
  const [input, setInput] = useState<BusinessProfileInput>(emptyBusinessProfileInput); const [state, setState] = useState(mode === "edit" ? "loading" : "ready"); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [review, setReview] = useState(false); const [prefix, setPrefix] = useState<string | null>(null); const [logo, setLogo] = useState<File | null>(null); const [removing, setRemoving] = useState(false);
  const preview = useMemo(() => logo ? URL.createObjectURL(logo) : input.logo_path, [logo, input.logo_path]);
  useEffect(() => () => { if (preview?.startsWith("blob:")) URL.revokeObjectURL(preview); }, [preview]);
  useEffect(() => { if (mode !== "edit") return; if (!Number.isInteger(id) || id <= 0) { setState("error"); return; } let mounted = true; void getBusinessProfile(id).then((profile) => { if (mounted) { setInput(businessProfileToInput(profile)); setPrefix(profile.invoice_prefix); setState("ready"); } }, () => mounted && setState("error")); return () => { mounted = false; }; }, [id, mode]);
  const update = <K extends keyof BusinessProfileInput>(field: K, value: BusinessProfileInput[K]) => setInput((current) => ({ ...current, [field]: value }));
  const chooseLogo = (file?: File) => { if (!file) return; if (!logoTypes.includes(file.type)) { setError("Bitte wählen Sie eine PNG-, JPEG- oder WebP-Datei aus."); return; } if (file.size > maxLogoSize) { setError("Das Logo darf maximal 5 MB groß sein."); return; } setError(null); setLogo(file); };
  const removeLogo = async () => { setError(null); if (logo) { setLogo(null); return; } if (mode !== "edit" || !input.logo_path) return; setRemoving(true); try { const profile = await removeBusinessProfileLogo(id); setInput(businessProfileToInput(profile)); } catch { setError("Das Logo konnte nicht entfernt werden."); } finally { setRemoving(false); } };
  const requestSave = (event: FormEvent) => { event.preventDefault(); const normalized = normalizeBusinessProfileInput(input); if (!normalized.business_name || !normalized.location_name || !normalized.street || !normalized.postal_code || !normalized.city || !normalized.iban) { setError("Bitte füllen Sie alle Pflichtfelder aus."); return; } setError(null); setReview(true); };
  const save = async () => { setSaving(true); setError(null); try { let profile = mode === "create" ? await createBusinessProfile(normalizeBusinessProfileInput(input)) : await updateBusinessProfile(id, normalizeBusinessProfileInput(input)); if (logo) profile = await uploadBusinessProfileLogo(profile.id, logo); navigate(`/business-profiles/${profile.id}`); } catch (caught) { setReview(false); setError(caught instanceof Error ? caught.message : "Der Betrieb oder Standort konnte nicht gespeichert werden."); } finally { setSaving(false); } };
  if (state === "loading") return <p className="business-loading" role="status">Betrieb oder Standort wird geladen …</p>;
  if (state === "error") return <section className="business-state"><p>Der Betrieb oder Standort wurde nicht gefunden.</p><Link className="business-button" to="/business-profiles">Zur Übersicht</Link></section>;
  return <section className="business-page" aria-labelledby="business-form-title"><header className="business-page__header"><div><h2 id="business-form-title">{mode === "create" ? "Betrieb / Standort anlegen" : "Betrieb / Standort bearbeiten"}</h2><p>Unternehmens-, Abrechnungs- und Bankdaten strukturiert verwalten.</p></div><Link className="business-button" to="/business-profiles">Zurück zur Übersicht</Link></header><form className="business-form" onSubmit={requestSave}><FormFields input={input} update={update} prefix={prefix} preview={preview} logo={logo} chooseLogo={chooseLogo} removeLogo={() => void removeLogo()} removing={removing} mode={mode}/>{error && <p className="business-error-text" role="alert">{error}</p>}<div className="business-form__actions"><Link className="business-button" to="/business-profiles">Abbrechen</Link><button className="business-button business-button--primary" disabled={saving} type="submit">{mode === "create" ? "Betrieb / Standort speichern" : "Änderungen speichern"}</button></div></form>{review && <Review input={input} prefix={prefix} mode={mode} logoName={logo?.name ?? (input.logo_path ? "Vorhandenes Logo" : "Kein Logo hinterlegt")} cancel={() => setReview(false)} confirm={() => void save()} saving={saving}/>}</section>;
}

function FormFields({ input, update, prefix, preview, logo, chooseLogo, removeLogo, removing, mode }: { input: BusinessProfileInput; update: <K extends keyof BusinessProfileInput>(field: K, value: BusinessProfileInput[K]) => void; prefix: string | null; preview: string | null; logo: File | null; chooseLogo: (file?: File) => void; removeLogo: () => void; removing: boolean; mode: "create" | "edit" }) { const field = (label: string, key: keyof BusinessProfileInput, required = false) => <label>{label}<input aria-label={label} onChange={(event) => update(key, event.target.value as never)} required={required} value={(input[key] as string | null) ?? ""}/></label>; return <><fieldset><legend>Stammdaten</legend><div className="business-form__grid">{field("Betriebsname", "business_name", true)}{field("Standortname", "location_name", true)}{field("Standortkürzel", "location_code")}</div></fieldset><fieldset><legend>Anschrift &amp; Kontakt</legend><div className="business-form__grid">{field("Straße", "street", true)}{field("PLZ", "postal_code", true)}{field("Ort", "city", true)}{field("Telefon", "phone")}{field("E-Mail", "email")}</div></fieldset><fieldset><legend>Steuer &amp; Identifikation</legend><div className="business-form__grid">{field("Steuernummer", "tax_number")}{field("Umsatzsteuer-Identifikationsnummer", "vat_id")}{field("IK-Nummer / Institutionskennzeichen", "ik_number")}</div></fieldset><fieldset><legend>Bankverbindung</legend><div className="business-form__grid">{field("IBAN", "iban", true)}{field("BIC", "bic")}{field("Bankname", "bank_name")}</div></fieldset><fieldset><legend>Logo &amp; Rechnungskennung</legend><div className="business-form__grid"><div className="business-logo-picker business-form__wide"><label className="business-button" htmlFor="business-logo">{preview ? "Logo ersetzen" : "Datei auswählen"}</label><input accept="image/png,image/jpeg,image/webp" id="business-logo" onChange={(event) => chooseLogo(event.target.files?.[0])} type="file"/><span>{logo?.name ?? (input.logo_path ? "Vorhandenes Logo" : "Kein Logo hinterlegt")}</span>{(logo || input.logo_path) && <button className="business-action-button" disabled={removing} onClick={removeLogo} type="button">{removing ? "Wird entfernt …" : "Entfernen"}</button>}{preview && <img alt="Logo-Vorschau" src={preview}/>}</div><label>Rechnungspräfix<input aria-label="Rechnungspräfix" disabled value={prefix ?? "Wird nach dem Speichern vergeben"}/></label></div><p className="business-hint">Das Rechnungspräfix wird automatisch vom Backend vergeben.</p></fieldset></>; }
function Review({ input, prefix, mode, logoName, cancel, confirm, saving }: { input: BusinessProfileInput; prefix: string | null; mode: "create" | "edit"; logoName: string; cancel: () => void; confirm: () => void; saving: boolean }) { const rows: [string, string | null][] = [["Betriebsname", input.business_name], ["Standortname", input.location_name], ["Standortkürzel", input.location_code], ["Straße", input.street], ["PLZ", input.postal_code], ["Ort", input.city], ["Telefon", input.phone], ["E-Mail", input.email], ["Steuernummer", input.tax_number], ["USt-IdNr.", input.vat_id], ["IK-Nummer", input.ik_number], ["IBAN", input.iban], ["BIC", input.bic], ["Bankname", input.bank_name], ["Logo", logoName], ["Rechnungspräfix", mode === "edit" ? prefix : "Wird beim Speichern vom Backend vergeben"]]; return <div className="business-dialog-backdrop"><section aria-labelledby="business-review-title" aria-modal="true" className="business-dialog business-dialog--review" role="dialog"><h2 id="business-review-title">Angaben prüfen</h2><div className="business-review-list">{rows.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value || "–"}</strong></div>)}</div><div><button className="business-button" onClick={cancel} type="button">Zurück und bearbeiten</button><button className="business-button business-button--primary" disabled={saving} onClick={confirm} type="button">{saving ? "Wird gespeichert …" : "Angaben bestätigen und speichern"}</button></div></section></div>; }
